Enabling clean up script for PowerVS Z stream
ppc64le-cloud/jenkins-infra pull request #224
Opened 2022-12-15 07:10 UTC by varad-ahirwadkar

Signed-off-by: Varad Ahirwadkar <varad.ahirwadkar@ibm.com>

2023-01-09 08:59 UTC, Shilpi-Das1 approved these changes
/lgtm

2023-01-09 09:11 UTC, Shilpi-Das1 requested changes

2023-01-09 09:11 UTC, Shilpi-Das1 commented on scripts/cleanup-powervs-resources.sh
>     ibmcloud login -a cloud.ibm.com -r us-south -g ibm-internal-cicd-resource-group -q --apikey=${IBMCLOUD_API_KEY}
This command will fail Can you add it to else statement

2023-01-12 05:16 UTC, varad-ahirwadkar commented
Closing this PR because moving all Z stream jobs from PowerVS to PowerVC.

2023-01-12 05:16 UTC, closed without merging